name: Run Twitter Bot

on:
  schedule:
    # Monday to Sunday (same schedule for consistency)
    - cron: "0 10 * * 0-6"  # 4:00 PM BD (10:00 AM UTC) → 6:00 AM ET / 3:00 AM PT (early morning)
    - cron: "0 14 * * 0-6"  # 8:00 PM BD (2:00 PM UTC) → 10:00 AM ET / 7:00 AM PT (morning peak)
    - cron: "0 22 * * 0-6"  # 4:00 AM BD (10:00 PM UTC) → 6:00 PM ET / 3:00 PM PT (evening peak)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run Twitter bot
        run: node index.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
