name: Run Twitter Bot

on:
  schedule:
    # Monday to Thursday
    - cron: "0 5 * * 1-4" # 5 AM UTC:11AM BD
    - cron: "0 11 * * 1-4" # 11 AM UTC:5PM BD
    - cron: "0 16 * * 1-4" # 4 PM UTC:10PM BD
    # Friday
    - cron: "0 5 * * 5" # 5 AM UTC:11AM BD
    - cron: "0 11 * * 5" # 11 AM UTC:5PM BD
    # Saturday
    - cron: "0 8 * * 6" # 8 AM UTC:2PM BD
    - cron: "0 14 * * 6" # 2 PM UTC:8PM BD
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run Twitter bot
        run: node index.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
